server:
  port: 8080
spring:
  application:
    name: "credit-application"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false
      path: "/h2"
  profiles:
    include: null
r2dbc:
  host: "${MYSQL_IP}"
  port: "${MYSQL_PORT}"
  database: "${MYSQL_DB}"
  username: "${MYSQL_USER}"
  password: "${MYSQL_PASSWORD}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    timeout: 5000
    url: "${ENDPOINT_USER_URL}"
  sqs:
    region: "${AWS_REGION}"
    queueUrl: "${AWS_SQS_URL}"
    endpoint: "${AWS_SQS_URL}"
  sns:
    region: "${AWS_SNS_REGION}"
    topicArn: "${AWS_SNS_TOPIC_ARN}"
adapter-deb:
  sqs:
    region: "${AWS_SQS_DEB_REGION}"
    queueUrl: "${AWS_SQS_DEB_URL}"
    endpoint: "${AWS_SQS_DEB_URL}"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"

jwt:
  secretKey: "${KEY_SECRET_AUTH_JWT}"
  expirationTime: 300
entrypoint:
  sqs:
    region: "${AWS_SQS_READ_REGION}"
    endpoint: "${AWS_SQS_READ_URL}"
    queueUrl: "${AWS_SQS_READ_QUEUE_URL}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
