services:

  app-auth-service:
    build:
      context: ./creditya-auth-service
      dockerfile: deployment/Dockerfile
    ports:
      - "8079:8079"
    environment:
      MYSQL_IP: 192.168.20.46
      MYSQL_PORT: 3306
      MYSQL_DB: CrediYaDB
      MYSQL_USER: fyroot
      MYSQL_PASSWORD: 1234
      REDIS_IP: 192.168.20.46
      REDIS_PORT: 6379
      KEY_SECRET_AUTH_JWT: 12345678901234567890-12345678901234567890

    networks:
      - crediya_network
  
  app-loan-service:
    build:
      context: ./creditya-loan-service
      dockerfile: deployment/Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_IP: 192.168.20.46
      MYSQL_PORT: 3306
      MYSQL_DB: CrediYaDB
      MYSQL_USER: fyroot
      MYSQL_PASSWORD: 1234
      REDIS_IP: 192.168.20.46
      REDIS_PORT: 3306
      KEY_SECRET_AUTH_JWT: 12345678901234567890-12345678901234567890
      AWS_REGION: us-east-2
      AWS_SQS_URL: https://sqs.us-east-2.amazonaws.com/817100478616/SQSStatusLoan
      AWS_SQS_URL: https://sqs.us-east-2.amazonaws.com/817100478616/SQSStatusLoan

    networks:
      - crediya_network
    depends_on:
      - app-auth-service
volumes:
  pg_data_auth:

networks:
  crediya_network:
    driver: bridge
