dependencies {
    implementation project(':model')
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.apache.logging.log4j:log4j-api'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.4.2'
    implementation 'software.amazon.awssdk:sns:2.33.11'
}
